"""initial tables

Revision ID: 085daf3367f0
Revises: d2dd62c70bf9
Create Date: 2025-10-17 13:38:56.985140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085daf3367f0'
down_revision: Union[str, Sequence[str], None] = 'd2dd62c70bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_pwd', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_document_users_id'), 'document_users', ['id'], unique=False)
    op.create_table('document_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['document_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_collection_id'), 'document_collection', ['id'], unique=False)
    op.create_table('document_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document_collection.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['document_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_files_checksum'), 'document_files', ['checksum'], unique=False)
    op.create_index(op.f('ix_document_files_document_id'), 'document_files', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_files_id'), 'document_files', ['id'], unique=False)
    op.create_index(op.f('ix_document_files_user_id'), 'document_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_files_user_id'), table_name='document_files')
    op.drop_index(op.f('ix_document_files_id'), table_name='document_files')
    op.drop_index(op.f('ix_document_files_document_id'), table_name='document_files')
    op.drop_index(op.f('ix_document_files_checksum'), table_name='document_files')
    op.drop_table('document_files')
    op.drop_index(op.f('ix_document_collection_id'), table_name='document_collection')
    op.drop_table('document_collection')
    op.drop_index(op.f('ix_document_users_id'), table_name='document_users')
    op.drop_table('document_users')
    # ### end Alembic commands ###
